#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyleft 2011 Pascal Spörri <pascal.spoerri@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import re
import subprocess
brutus_options = '-R "rusage[gpu=1]"'
command = 'BGPU_CSELAB -solver PS -tend 10.0 -dt 0.01 -file {file} -dumpperiod 1 -prefix {prefix}_dt0.01_tend10.0_t0.5 -theta 0.5'

files = os.listdir('.')

fileprefix = 'circles_'
for filename in files:
  if re.match(fileprefix,filename):
    subprocess.check_output('echo {filename}'.format(filename=filename),
        stderr=subprocess.STDOUT,
        shell=True)
