#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyleft 2011 Pascal Spörri <pascal.spoerri@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
"select[gputype==Fermi]"# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import re
import subprocess
import time

brutus_command = 'bsub'
brutus_options = '-R "select[gputype==Fermi]"'
command = 'BGPU_CSELAB -solver PS -tend 10.0 -dt 0.01 -file {file} -dumpperiod 10 -prefix {prefix}_USING_BGPU_dt0.01_tend10.0_t0.5 -theta 0.5'

files = os.listdir('.')

fileprefix = 'circles_'
for filename in files:
    cmd_prepared = command.format(file=filename,
        prefix=filename)
    cmd = '{bcmd} {bopts} {cmd}'.format(bcmd=brutus_command,
        bopts=brutus_options,
        cmd=cmd_prepared)
    print "Executing ",cmd
    subprocess.check_call(cmd,shell=True)
    time.sleep(2) # Wait 5 seconds to start the next job
